package cab302.viewer.exceptions;


public class MalformedHexadecimalColourException extends Exception {
    /**
     * Exception generated by the HexToRGB class if a Hexadecimal string is not a
     * valid colour
     * @param message The message to send when thrown
     */
    public MalformedHexadecimalColourException(String message) {
        super(message);
    }
}
